# This configuration file contains the directories that are needed to be seen by (binded to) the spack-stack container. 
# The variables are sourced in the make-external script, which is used to create the wrapper scripts.

# This variable is updated via sed command in the convert-modules.py script
INIT_LOCAL_DIRS=

# This variable is updated via sed command in the update_ss_container_compilers.sh script
NEW_COMPILER_DIRS=
